name: dst
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - pip
  - pytorch
  - cudatoolkit=10.2
  - transformers
  - tensorboard
  - omegaconf
  - pip:
      - numpy
      - matplotlib
      - scipy
      - pandas
