name: dst
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - pip
  - keras
  - transformers
  - sentencepiece
  - tensorboard
  - omegaconf
  - click
  - tqdm
  - fuzzywuzzy
  - pygithub
  - pip:
    - jupyter
    - numpy
    - matplotlib
    - scipy
    - pandas
    - nltk

# python -m pip install -U torch==1.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
