name: d3st
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - pip==22.0.3
  - keras==2.6.0
  - transformers==4.16.2
  - sentencepiece==0.1.96
  - tensorboard==2.8.0
  - omegaconf==2.1.1
  - click==8.1.1
  - tqdm==4.62.3
  - fuzzywuzzy==0.18.0
  - pygithub==1.55
  - pip:
    - jupyter==1.0.0
    - numpy==1.22.2
    - matplotlib==3.5.1
    - scipy==1.7.2
    - pandas==1.4.1
    - nltk==3.7
    - setuptools==59.5.0

# python -m pip install -U torch==1.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
