CATEGORICALS_WITH_DONTCARE_VALUE = {
    "Banks_1": ["recipient_account_type"],
    "Banks_11": ["recipient_account_type"] + ["recipient_type"],
    "Banks_12": ["recipient_account_type"] + ["transfer_target_acct_type"],
    "Banks_13": ["recipient_account_type"] + ["type_of_account_for_recipient"],
    "Banks_14": ["recipient_account_type"] + ["account_type_of_recipient"],
    "Banks_15": ["recipient_account_type"] + ["account_type_receiving_transfer"],
    "Banks_2": ["recipient_account_type"],
    "Banks_21": ["recipient_account_type"] + ["receiving_account_type"],
    "Banks_22": ["recipient_account_type"] + ["recipient_bank_account_type"],
    "Banks_23": ["recipient_account_type"] + ["target_account_type"],
    "Banks_24": ["recipient_account_type"] + ["transfer_recipient_account_type"],
    "Banks_25": ["recipient_account_type"] + ["account_type_of_transferee"],
    "Buses_2": ["fare_type"],
    "Buses_21": ["fare_type"] + ["fare_class"],
    "Buses_22": ["fare_type"] + ["type_of_fare"],
    "Buses_23": ["fare_type"] + ["booking_fare"],
    "Buses_24": ["fare_type"] + ["fare_description"],
    "Buses_25": ["fare_type"] + ["booking_class"],
    "Buses_3": ["category"],
    "Buses_31": ["category"] + ["stops"],
    "Buses_32": ["category"] + ["route_stops"],
    "Buses_33": ["category"] + ["total_stops"],
    "Buses_34": ["category"] + ["bus_route_stops"],
    "Buses_35": ["category"] + ["number_of_stops"],
    "Flights_1": ["airlines", "seating_class"],
    "Flights_11": ["airlines", "seating_class"] + ["airline", "seat_class"],
    "Flights_12": ["airlines", "seating_class"] + ["airline_name", "cabin_class"],
    "Flights_13": ["airlines", "seating_class"] + ["carrier", "travel_class"],
    "Flights_14": ["airlines", "seating_class"] + ["name_of_airline", "class"],
    "Flights_15": ["airlines", "seating_class"]
    + ["commercial_airline", "class_seating"],
    "Flights_2": ["airlines", "seating_class"],
    "Flights_21": ["airlines", "seating_class"] + ["airline", "seat_class"],
    "Flights_22": ["airlines", "seating_class"] + ["airline_name", "class_of_seats"],
    "Flights_23": ["airlines", "seating_class"] + ["airline_to_book", "class_type"],
    "Flights_24": ["airlines", "seating_class"]
    + ["airline_companies", "flight_ticket_class"],
    "Flights_25": ["airlines", "seating_class"]
    + ["name_of_airline", "class_preference"],
    "Flights_3": ["airlines", "flight_class"],
    "Flights_31": ["airlines", "flight_class"] + ["airline", "fare_class"],
    "Flights_32": ["airlines", "flight_class"] + ["airline_name", "flight_fare_class"],
    "Flights_33": ["airlines", "flight_class"] + ["provider", "seat_class"],
    "Flights_34": ["airlines", "flight_class"] + ["class", "flight_name"],
    "Flights_35": ["airlines", "flight_class"]
    + ["operating_airline", "class_of_flights"],
    "Flights_4": ["airlines", "seating_class"],
    "Flights_41": ["airlines", "seating_class"] + ["airline", "seat_class"],
    "Flights_42": ["airlines", "seating_class"] + ["airline_name", "seating_choices"],
    "Flights_43": ["airlines", "seating_class"] + ["company", "seat_choice"],
    "Flights_44": ["airlines", "seating_class"] + ["company_name", "cabin_seat_class"],
    "Flights_45": ["airlines", "seating_class"]
    + ["air_transport_services_company_name", "seat_option"],
    "Media_2": ["subtitle_language"],
    "Media_21": ["subtitle_language"] + ["subtitles_language"],
    "Media_22": ["subtitle_language"] + ["caption_language"],
    "Media_23": ["subtitle_language"] + ["subtitle_options"],
    "Media_24": ["subtitle_language"] + ["closed_caption_language"],
    "Media_25": ["subtitle_language"] + ["language_of_subtitles"],
    "Media_3": ["subtitle_language"],
    "Media_31": ["subtitle_language"] + ["movie_subtitle_language"],
    "Media_32": ["subtitle_language"] + ["subtitles"],
    "Media_33": ["subtitle_language"] + ["language"],
    "Media_34": ["subtitle_language"] + ["closed_caption_language"],
    "Media_35": ["subtitle_language"] + ["language_of_subtitles"],
    "Movies_1": ["show_type"],
    "Movies_11": ["show_type"] + ["movie_type"],
    "Movies_12": ["show_type"] + ["visuals_type"],
    "Movies_13": ["show_type"] + ["show_category"],
    "Movies_14": ["show_type"] + ["presentation_type"],
    "Movies_15": ["show_type"] + ["type_of_show"],
    "Music_1": ["playback_device"],
    "Music_11": ["playback_device"] + ["playback_device_name"],
    "Music_12": ["playback_device"] + ["playing_on_device"],
    "Music_13": ["playback_device"] + ["device"],
    "Music_14": ["playback_device"] + ["player"],
    "Music_15": ["playback_device"] + ["audio_output_device"],
    "Music_2": ["playback_device"],
    "Music_21": ["playback_device"] + ["select_device"],
    "Music_22": ["playback_device"] + ["audio_device"],
    "Music_23": ["playback_device"] + ["device"],
    "Music_24": ["playback_device"] + ["device_name"],
    "Music_25": ["playback_device"]
    + [
        "device_to_play_song",
    ],
    "Music_3": ["device"],
    "Music_31": ["device"] + ["playback_device"],
    "Music_32": ["device"] + ["media_player"],
    "Music_33": ["device"] + ["media_player_name"],
    "Music_34": ["device"] + ["playback_location"],
    "Music_35": ["device"] + ["name_of_media_player"],
    "RentalCars_1": ["type"],
    "RentalCars_11": ["type"] + ["car_type"],
    "RentalCars_12": ["type"] + ["category"],
    "RentalCars_13": ["type"] + ["rental_car_type"],
    "RentalCars_14": ["type"] + ["car_rental_category"],
    "RentalCars_15": ["type"] + ["rental_car_category"],
    "RentalCars_2": ["car_type"],
    "RentalCars_21": ["car_type"] + ["rental_type"],
    "RentalCars_22": ["car_type"] + ["vehicle_type"],
    "RentalCars_23": ["car_type"] + ["car_rental_type"],
    "RentalCars_24": ["car_type"] + ["type_of_car"],
    "RentalCars_25": ["car_type"] + ["rental_car_class"],
    "RentalCars_3": ["car_type"],
    "RentalCars_31": ["car_type"] + ["car_style"],
    "RentalCars_32": ["car_type"] + ["auto_type"],
    "RentalCars_33": ["car_type"] + ["vehicle_type"],
    "RentalCars_34": ["car_type"] + ["type_of_car"],
    "RentalCars_35": ["car_type"] + ["hatchback_sedan_or_suv"],
    "Restaurants_1": ["price_range"],
    "Restaurants_11": ["price_range"] + ["menu_price_range"],
    "Restaurants_12": ["price_range"] + ["pricing"],
    "Restaurants_13": ["price_range"] + ["price"],
    "Restaurants_14": ["price_range"] + ["restaurant_price_range"],
    "Restaurants_15": ["price_range"] + ["estimated_price_band"],
    "Restaurants_2": ["price_range"],
    "Restaurants_21": ["price_range"] + ["cost_range"],
    "Restaurants_22": ["price_range"] + ["estimated_price_range"],
    "Restaurants_23": ["price_range"] + ["restaurant_price_range"],
    "Restaurants_24": ["price_range"] + ["restaurant_prices"],
    "Restaurants_25": ["price_range"] + ["restaurant_range_of_price"],
    "Trains_1": ["class"],
    "Trains_11": ["class"] + ["fare_class"],
    "Trains_12": ["class"] + ["train_fare_class"],
    "Trains_13": ["class"] + ["class_of_reservation"],
    "Trains_14": ["class"] + ["reservation_fare_class"],
    "Trains_15": ["class"] + ["fare_class_for_reservation"],
    "Travel_1": ["category"],
    "Travel_11": ["category"] + ["type"],
    "Travel_12": ["category"] + ["attraction_category"],
    "Travel_13": ["category"] + ["attraction_type"],
    "Travel_14": ["category"] + ["category_of_attraction"],
    "Travel_15": ["category"] + ["type_of_attraction"],
}
ALPHA_NUMERIC_SLOT_EXCEPTIONS = {"movie_rating_out_of_10"}
_DONTCARE_HANDLING_OPTIONS = {"predict_dontcare", "qa_option"}
