metadata:
  preprocessing_method: 'd3st_paper_double_pipe'
preprocessing:
  target_slot_index_separator: ":"
  prefix_separators:
    categorical_slots: ':'
    noncategorical_slots: "="
    intents: "="
  special_tokens:
    - "[user]"
    - "[system]"
    - "[states]"
    - "[intents]"
    - "[req_slots]"
  # choose between "heuristic" (carries over values that have been said before)
  # and "concatenate" which forms a string "val_1|val_2" from a list [val_1,val_2]
  value_selection:
    method: "concatenate"
    value_separator: " || "
    # changes the order wrt annotation before concatenation
    shuffle_before_concat: true
  lowercase_model_inputs: true
  lowercase_model_targets: true
# only 1 out of downsample_factor dialogues is processed; used to reduce the training data
# quantity
downsample_factor: 1
downsample_mode: 'dialogue'
reproduce:
  seed: 20220303 # same seed for random, NumPy, PyTorch (CPU/GPU), across devices
  cudnn:
    enabled: True
    deterministic: False
    benchmark: True
