metadata:
  preprocessing_method: 'd3st_paper'
preprocessing:
  prefix_separators:
    categorical_slots: ':'
    noncategorical_slots: "="
    intents: "="
  special_tokens:
    - "[user]"
    - "[system]"
    - "[states]"
    - "[intents]"
    - "[req_slots]"
  # choose between "heuristic" (carries over values that have been said before)
  # and "concatenate" which forms a string "val_1|val_2" from a list [val_1,val_2]
  value_selection:
    method: "concatenate"
    value_separator: "|"
    # changes the order wrt annotation before concatenation
    shuffle_before_concat: true
  lowercase_model_inputs: true